name: Build docker image and release with Octopus

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

env:
  REGISTRY_NAME: ${{ secrets.CONTAINER_REGISTRY_NAME }}
  REGISTRY: ${{ secrets.CONTAINER_REGISTRY_URL }}
  IMAGE_NAME: OctopusDeployTesting/dad-joker-2000
  OCTOPUS_SPACE: Demo

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get release version
        id: get_release_version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          version_format: "${major}.${minor}.${patch}"

      - name: Get branch names
        id: branch_names
        uses: OctopusDeploy/util-actions/current-branch-name@current-branch-name.0.1.0

      - name: Get pre-release version
        id: get_pre_release_version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          version_format: "${major}.${minor}.${patch}-${{ github.event_name == 'pull_request' && 'pr-' || '' }}${{ github.event_name == 'pull_request' && github.event.pull_request.number || steps.branch_names.outputs.branch_name }}.${{ github.run_number }}-${{ github.run_attempt }}"

      - name: Get version
        id: get_version
        run: echo "version=${{ github.ref == 'refs/heads/main' && github.event_name == 'push' && steps.get_release_version.outputs.version || steps.get_pre_release_version.outputs.version }}" >> $GITHUB_OUTPUT

      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to Container Registry
        run: |
          az acr login --name ${{ env.REGISTRY_NAME }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Extract metadata (tags, labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=raw,value=${{ steps.get_version.outputs.version }}
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      # Build and push Docker image with Buildx
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}          
          annotations: ${{ steps.meta.outputs.annotations }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  test_environment:
    name: Deploy to test environment
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Login to Octopus Deploy
        uses: OctopusDeploy/login@v1
        with:
          server: ${{ secrets.OCTOPUS_SERVER_URL }}
          service_account_id: ${{ secrets.OCTOPUS_SERVICE_ACCOUNT_ID }}

      - name: Create test environment
        uses: OctopusDeploy/create-ephemeral-environment@v1.0.0
        with:
          name: pr-${{ github.event.pull_request.number }}
          project: Dad Joker 2000

      - name: Create test environment release
        uses: OctopusDeploy/create-release-action@v3
        with:
          project: Dad Joker 2000
          release_number: ${{ needs.build.outputs.version }}
          channel: Test environments
          git_ref: ${{ github.head_ref }}
          git_commit: ${{ github.event.pull_request.head.sha }}
          package_version: ${{ needs.build.outputs.version }}
          custom_fields: |
            PullRequestNumber: ${{ github.event.pull_request.number }}

      - name: Deploy the test environment release
        id: deploy_step
        uses: OctopusDeploy/deploy-release-action@v3
        with:
          project: Dad Joker 2000
          release_number: ${{ needs.build.outputs.version }}
          environments: |
            pr-${{ github.event.pull_request.number }}

      - name: Wait for deployment to complete
        uses: OctopusDeploy/await-task-action@v3
        with:
          server_task_id: ${{ fromJSON(steps.deploy_step.outputs.server_tasks)[0].serverTaskId }}
          polling_interval: 2s

  production:
    name: Create production release and tag repo
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Login to Octopus Deploy
        uses: OctopusDeploy/login@v1
        with:
          server: ${{ secrets.OCTOPUS_SERVER_URL }}
          service_account_id: ${{ secrets.OCTOPUS_SERVICE_ACCOUNT_ID }}

      - name: Create production release
        uses: OctopusDeploy/create-release-action@v3
        with:
          project: Dad Joker 2000
          release_number: ${{ needs.build.outputs.version }}
          channel: Production
          git_ref: ${{ github.ref }}
          git_commit: ${{ github.sha }}
          package_version: ${{ needs.build.outputs.version }}

      - name: Tag repo on main branch
        uses: actions/github-script@v6.3.3
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ needs.build.outputs.version }}',
              sha: context.sha
            })
